# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaadd', models.DateField()),
                ('fechadev', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.Cliente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAlquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alquileres.Alquiler')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.Formato')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
