# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_detallealquiler_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallealquiler',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
